parameters:
- componentType: scope
  label: Jamf Protect Logs data source
  keyTfVar: scope_key1
  defaultValueTfVar: default_scope_value1
- componentType: scope
  label: Jamf Security Cloud Logs data source
  keyTfVar: scope_key
  defaultValueTfVar: default_scope_value
